### ISSUE TITLE
FTS5 support

### ISSUE THREAD

**Issue by NeomMob** [smourier/SQLNado#7]
Hi,
Is there a way to use FTS5 using SQLNado? I am looking for a way to have a custom tokenizer for FTS5.

Thanks!

**Comment by smourier** [comment]
Hi,

Sure, just declare the class / table like this for example:

    [SQLiteTable(Module = "fts5", ModuleArguments = nameof(Body) + "," + nameof(Whatever))]
    public class Search
    {
        [SQLiteColumn(IsPrimaryKey = true)]
        public long RowId { get; set; }
        public string Body { get; set; }
        public string Whatever { get; set; }
    }

But note the winsqlite3.dll that comes with Windows 10 (and Azure web apps) doesn't include the FTS5 unfortunately, so you'll have to get sqlite binary from sqlite.org, or directly use the ones I put here: https://github.com/smourier/SQLNado/tree/master/SqlNado (they are already renamed so it's easier to use)

**Comment by NeomMob** [comment]
Thanks for your speedy andwer.
Regarding the Custom Tokenizer, it has to be a completly brand new implementataion or can I reuse the existing one?

**Comment by smourier** [comment]
You can't derive (in a .NET way) from an existing tokenizer but you can reuse its code with this function in SQLiteDatabase:

    public SQLiteTokenizer GetTokenizer(string name, params string[] arguments)

or directly these wrappers:

    public SQLiteTokenizer GetSimpleTokenizer(params string[] arguments) => GetTokenizer("simple", arguments);
    public SQLiteTokenizer GetPorterTokenizer(params string[] arguments) => GetTokenizer("porter", arguments);
    public SQLiteTokenizer GetUnicodeTokenizer(params string[] arguments) => GetTokenizer("unicode61", arguments);

However, I have two remarks:
* the existing tokenizers are really not rocket science and it's relatively easy to write a whole one by yourself
* in general, I found easier to build a unique custom field (like Body in my example) that contain all the tokens I need (removing stop words, etc.), instead of sending a table with lots of columns and customizing tokenizers at all

**Comment by NeomMob** [comment]
I am planning to create a fully custom one [as explained here](https://sqlite.org/fts5.html#custom_tokenizers) but was just wondering how to get the `fts5_api` from SQLNado

**Comment by smourier** [comment]
SQLNado doesn't support the fts5 tokenizers, only the fts5 storage & query, so if you really want that you'll have to add some serious interop code, you can have a look at SQLiteDatabase.cs for some insights.
